branches:
  only:
    - master

script:
  - echo `date "+%Y-%m-%d_%H_%M_%S"` > deploy.txt

before_deploy:
  - git config --local user.name asalom
  - git config --local user.email $GITHUB_EMAIL
  - git add deploy.txt
  - git commit -m "add deploy.txt"
  - git tag `date "+%Y-%m-%d_%H_%M_%S"`

deploy:
  on:
    branch: master
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: deploy.txt
