branches:
  only:
    - master

script:
  - echo 'Hello world'

before_deploy:
  - git config --local user.name asalom
  - git config --local user.email $GITHUB_EMAIL
  - git tag `date "+%Y-%m-%d_%H_%M"`

deploy:
  on:
    branch: master
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
